-- Lista inicial de competições e elenco, fornecida pelo usuário.
-- Papéis e apelidos só foram informados para 3 pessoas (Casimiro Miguel,
-- Luís Felipe Freitas, Raony Pacheco) — as demais entram sem papel padrão
-- definido; isso é só preenchido depois, na interface.

INSERT OR IGNORE INTO competicoes (nome, criado_em) VALUES
  ('Copa Davis de Tênis', datetime('now')),
  ('Circuito ATP de Tênis', datetime('now')),
  ('Ligue 1 - Campeonato Francês', datetime('now')),
  ('La Liga - Campeonato Espanhol', datetime('now')),
  ('Bundesliga - Campeonato Alemão', datetime('now')),
  ('Brasileirão - Campeonato Brasileiro', datetime('now')),
  ('Premiere League - Campeonato Inglês', datetime('now')),
  ('Copa do Mundo Feminina Sub-20 2026', datetime('now')),
  ('Copa do Mundo FIFA 2026', datetime('now')),
  ('Serie A - Campeonato Italiano', datetime('now')),
  ('WTT de Tênis de Mesa', datetime('now')),
  ('UEFA Europa League - Liga Europa', datetime('now')),
  ('UEFA Conference League - Liga Conferência', datetime('now'));

INSERT OR IGNORE INTO pessoas (nome, apelidos, papeis_padrao, criado_em) VALUES
  ('Alexandre Branco', '["Alezudo"]', '[]', datetime('now')),
  ('Aline Gomes', '[]', '[]', datetime('now')),
  ('Amanda Viana', '[]', '[]', datetime('now')),
  ('Ana Helena Goebel', '[]', '[]', datetime('now')),
  ('André Marques', '[]', '[]', datetime('now')),
  ('Bárbara Coelho', '[]', '[]', datetime('now')),
  ('Bruna Dealtry', '[]', '[]', datetime('now')),
  ('Bruno Magalhães', '[]', '[]', datetime('now')),
  ('Caio Ricard', '[]', '[]', datetime('now')),
  ('Casimiro Miguel', '["Cazé"]', '["apresentador","comentarista"]', datetime('now')),
  ('Day Natale', '[]', '[]', datetime('now')),
  ('Djalminha', '[]', '[]', datetime('now')),
  ('Felipe Leite', '[]', '[]', datetime('now')),
  ('Fernanda Gentil', '[]', '[]', datetime('now')),
  ('Fernando Campos', '[]', '[]', datetime('now')),
  ('Fernando Nardini', '[]', '[]', datetime('now')),
  ('Fred Caldeira', '[]', '[]', datetime('now')),
  ('Gabriel Simões', '[]', '[]', datetime('now')),
  ('Gonçalo Luiz', '[]', '[]', datetime('now')),
  ('Guilherme Beltrão', '[]', '[]', datetime('now')),
  ('Henrique Mathias', '[]', '[]', datetime('now')),
  ('Igor Rodrigues', '[]', '[]', datetime('now')),
  ('Isabela Pagliari', '[]', '[]', datetime('now')),
  ('João Barretto', '[]', '[]', datetime('now')),
  ('Juliana Cabral', '[]', '[]', datetime('now')),
  ('Laura Luzzi', '[]', '[]', datetime('now')),
  ('Letícia Macedo', '[]', '[]', datetime('now')),
  ('Lucas Pedrosa', '[]', '[]', datetime('now')),
  ('Lucca Bopp', '[]', '[]', datetime('now')),
  ('Luciana Zogaib', '[]', '[]', datetime('now')),
  ('Luís Felipe Freitas', '["Luizinho"]', '["apresentador","narrador"]', datetime('now')),
  ('Luís Folha', '[]', '[]', datetime('now')),
  ('Maércio Júnior', '[]', '[]', datetime('now')),
  ('Michelle Silva', '[]', '[]', datetime('now')),
  ('Marcus Carvalho', '[]', '[]', datetime('now')),
  ('Rafa Penido', '[]', '[]', datetime('now')),
  ('Rafael Oliveira', '[]', '[]', datetime('now')),
  ('Raony Pacheco', '["Raoni"]', '["apresentador","narrador"]', datetime('now')),
  ('Robert Almeida', '[]', '[]', datetime('now')),
  ('Tartá', '[]', '[]', datetime('now')),
  ('Vitor Costa', '[]', '[]', datetime('now'));
